export const actionTypes ={
    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

    FETCH_PRODUCTS_BEGIN: 'FETCH_PRODUCTS_BEGIN',
    FETCH_PRODUCTS_SUCCESS:'FETCH_PRODUCTS_SUCCESS',
    FETCH_PRODUCTS_FAILURE: 'FETCH_PRODUCTS_FAILURE',

    FETCH_PRODUCT_BEGIN: 'FETCH_PRODUCT_BEGIN',
    FETCH_PRODUCT_SUCCESS:'FETCH_PRODUCT_SUCCESS',
    FETCH_PRODUCT_FAILURE:'FETCH_PRODUCT_FAILURE'
}


